language: java
jdk:
- openjdk8
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
install: true
script:
- "./gradlew :oeqPrimaryB2:clean :oeqPrimaryB2:buildB2 :oeqPrimaryWS:clean :oeqPrimaryWS:buildWS :oeqLinkMigrationLTI:clean :oeqLinkMigrationLTI:buildLinkMigration"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
deploy:
  provider: releases
  api_key:
    secure: MzWFKdAThHjAUG1HIxrFTkKBTRg8G+x7lgjUHVkBkLBGrNYvEmgIbbk1aVYBIVJM8gSuQTiXYjI4ivzicDjeWJNGwINYtxDFvYvOBrlSezrmPzt6weCaCjVP6t40nbFilyA+YaoR1/l3hvwST+MQ+iMNYhRWcgKErbVUnhRztON0nYaBY2CEnh6agU4Ax9ltCkMsbUcN1vCwwGSzu4f7h6CxAk7K/x+rAmBz7VTTvb/MocY5Xn96SB+JvajVQjHhicyn7o0BGdWpwFZcky++SpIAOomjDeVin/5pm01z/lHDpMP8+W1rtARFQU5VWFv2JfeCXNmp5uxxwtIMb+16z7KmduI4SrYVaUYa33vRGAg733417c4mBt0XT7IRmoz6yHjYfwtVfHij2/Ynt+U2rtrBRmkwho+5MJs21fJ8pN7oasBBdIWc1J9ZzUPrvcYSvOjqi/rHtmqlBGioJAVFxRDxgPNGCosyWT2oMz0RsLM2GdnLXzwPWDUIUU/lEy175s4e+NC4hFf5PslVMPpSsNt7U01vS/kvol8gepLpDWSlXi4/teI6Z+SV6+kUnBUS0lAngNeSOxwQqmicwW4BMSxcr9YLk/BjcuX+v6BQzznF2NS9Ab6bU6/0Pgl34Ngj86kgBxzAn0zs/yWtEM2Y4Hn3E5SpCcihis4ZxWVHCbY=
  file_glob: true
  file: 
  - oeqPrimaryB2/build/libs/*
  - oeqPrimaryWS/build/libs/*
  - oeqLinkMigrationLTI/build/libs/*
  skip_cleanup: true
  on:
    tags: true
    repo: openequella/openEQUELLA-blackboard-integration
